### ISSUE TITLE
How to get csv in train_gnn.py

### ISSUE THREAD

**Issue by xtjjyygy** [RomeoV/ml4co-competition#17]
Hello RomeoV,It's a great honor to see this open source code,My question is how to get tain_gnn.py CSV file at line 148 and line 166, thank you

**Comment by RomeoV** [comment]
I just zipped and pushed them to the repository.

```
git checkout feature/final-submission; git pull
cd ml4co-competition/bo_gnn/config
tar -xf data.tar.gz
```

Feel free to reopen this issue if there are any problems.

Cheers,
Romeo
